/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package tn.insat.iac;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int fond=0x7f020000;
        public static final int ic_launcher=0x7f020001;
    }
    public static final class id {
        public static final int firstname=0x7f050001;
        public static final int lastname=0x7f050002;
        public static final int listView=0x7f050000;
        public static final int mail=0x7f050003;
        public static final int save=0x7f050004;
    }
    public static final class layout {
        public static final int activity_list_friend=0x7f030000;
        public static final int register=0x7f030001;
        public static final int text_view=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
